version: '2'

services:
  application:
    build: containers/volumes
    container_name: expedia.volumes
    volumes:
      - .:/var/www/expedia

  apache:
    image: php:5.6-apache
    restart: always
    container_name: expedia.apache
    working_dir: /var/www/expedia
    volumes:
      - ./containers/config/apache/sites-enabled:/etc/apache2/sites-enabled
    environment: 
      - "APACHE_LOG_DIR=/var/www/expedia/logs"
    expose:
      - 80
    ports:
      - 3000:80
    volumes_from:
      - application
